# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Project_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from os import error
from PyQt5 import QtCore, QtGui, QtWidgets
from PySide2 import QtCore, QtGui, QtWidgets
from PySide2.QtCore import (QCoreApplication, QPropertyAnimation, QDate, QDateTime, QMetaObject, QObject, QPoint, QRect, QSize, QTime, QUrl, Qt, QEvent)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont, QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter, QPixmap, QRadialGradient)
from PySide2.QtWidgets import *
import pandas as pd


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(801, 565)
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(123, 100, 161, 21))
        self.textEdit.setObjectName("textEdit")
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(550, 130, 151, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(Dialog)
        self.comboBox_3.setGeometry(QtCore.QRect(120, 140, 161, 21))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(300, 30, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(540, 100, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 140, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(40, 180, 721, 321))
        # self.tableWidget.setRowCount(3)
        # self.tableWidget.setColumnCount(6)
        self.tableWidget.setObjectName("tableWidget")
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setHorizontalHeaderItem(0, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setHorizontalHeaderItem(1, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setHorizontalHeaderItem(2, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setHorizontalHeaderItem(3, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setHorizontalHeaderItem(4, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setHorizontalHeaderItem(5, item)
        self.textEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(630, 100, 104, 21))
        self.textEdit_2.setObjectName("textEdit_2")
        self.loadBtn = QtWidgets.QPushButton(Dialog)
        self.loadBtn.setGeometry(QtCore.QRect(380, 140, 75, 23))
        self.loadBtn.setObjectName("loadBtn")
        self.loadBtn.clicked.connect(self.loadData)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Hotel Analytics"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "Binary Search"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "Linear Search"))
        self.comboBox_3.setItemText(0, _translate("Dialog", "Selection Sort"))
        self.comboBox_3.setItemText(1, _translate("Dialog", "Insertion Sort"))
        self.comboBox_3.setItemText(2, _translate("Dialog", "Merge Sort"))
        self.comboBox_3.setItemText(3, _translate("Dialog", "Quick Sort"))
        self.comboBox_3.setItemText(4, _translate("Dialog", "Counting Sort"))
        self.comboBox_3.setItemText(5, _translate("Dialog", "Hybrid Sort"))
        self.comboBox_3.setItemText(6, _translate("Dialog", "Bubble Sort"))
        self.label.setText(_translate("Dialog", "HOTEL ANALYTICS"))
        self.pushButton.setText(_translate("Dialog", "Search"))
        self.pushButton_2.setText(_translate("Dialog", "Sort"))
        # item = self.tableWidget.horizontalHeaderItem(0)
        # item.setText(_translate("Dialog", "Name"))
        # item = self.tableWidget.horizontalHeaderItem(1)
        # item.setText(_translate("Dialog", "Location"))
        # item = self.tableWidget.horizontalHeaderItem(2)
        # item.setText(_translate("Dialog", "Charges"))
        # item = self.tableWidget.horizontalHeaderItem(3)
        # item.setText(_translate("Dialog", "No of Rooms"))
        # item = self.tableWidget.horizontalHeaderItem(4)
        # item.setText(_translate("Dialog", "Ratings"))
        # item = self.tableWidget.horizontalHeaderItem(5)
        # item.setText(_translate("Dialog", "Reviews"))
        self.loadBtn.setText(_translate("Dialog", "Load Data"))
    def loadData(self):
        try:
                self.all_data = pd.read_csv('Hotels2.csv')
        except error:
                print(error)
        NumRows = len(self.all_data.index)
        self.tableWidget.setColumnCount(len(self.all_data.columns))
        self.tableWidget.setRowCount(NumRows)
        self.tableWidget.setHorizontalHeaderLabels(self.all_data.columns)
        for i in range(NumRows):
                for j in range(len(self.all_data.columns)):
                        self.tableWidget.setItem(i, j, QTableWidgetItem(str(self.all_data.iat[i, j])))

        self.tableWidget.resizeColumnsToContents()
        self.tableWidget.resizeRowsToContents()
    def array(self):
        Hotel_name=[]
        Address=[]
        Reviews=[]
        Charges=[]
        Rooms=[]
        Ratings=[]
        with open('Hotels2.csv', mode='r', enconding='utf-8')as file:
            csvFile=csv.reader(file)
            for line in csvFile:
                Hotel_name.oppend(line[0])
                Reviews.oppend(line[1])
                Charges.oppend(line[2])
                Rooms.oppend(line[3])
                Ratings.oppend(line[4])
            




        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
